### ISSUE TITLE
Double clicks are feeling unresponsive

### ISSUE THREAD

**Issue by DelVision** [nucleon/wintertodt-scouter#5]
For some reason I have to spam click the worlds to have world hop register, and sometimes it takes like 10 clicks to actual work.

As an additional note, just single click option for world hopping would be also really nice, because there isn't really any other reason to click the worlds in the list anyway.. So it would just make the switch slightly faster

**Comment by nucleon** [comment]
how do your clicks behave using the other world hopper plugin?

**Comment by DelVision** [comment]
No issues with the double clicks using that one, works with every double click..

Also interestingly using the world hopper plugin seems to have fixed the issue with wintertodt scouter, after using the world hopper plugin once the clicks became more responsive with the scouter too.

I have always used hotkeys to world hop with the other plugin, so maybe that's why I had problems with the double clicks

**Comment by TrevorMDev** [comment]
I can second this issue, including the fix of double clicking on the normal world hopper plugin made it go away.

**Comment by nucleon** [comment]
I tried to fix it when this issue was made but my account was banned (nucleon) shortly after. I think I may have automated something with the world hop list that flagged runelite. I didn’t push the fix, I’m awaiting Jagex response.


I can ask my friend Cyborger1 to look at this issue if it’s still not going away. He’s very familiar with the world lists.
